/// Route ids that reuse another module's RBAC rule.
///
/// Nav item ids in the owner module pack stay distinct (`markbook` vs
/// `examinations`). This map is only for permission / allocation lookup.
const Map<String, String> kModuleIdAliases = {
  'staff': 'hr',
  'employees': 'hr',
  'payroll': 'hr',
  'add_teacher': 'hr',
  'add_staff': 'teachers',
  'grades': 'examinations',
  'grade_approvals': 'examinations',
  'transport_buses': 'transport',
  'transport_live_gps': 'transport',
  'add_driver': 'transport',
  'add_student': 'students',
  'timetable': 'academic',
  'student_portal_settings': 'school',
  'student_password_resets': 'students',
  'grade_workflow_settings': 'examinations',
  'markbook': 'examinations',
  'report_cards': 'examinations',
  'exam_bank': 'examinations',
  'exam_papers': 'examinations',
  'exam_desk': 'examinations',
  'lms': 'academic',
  'lesson_plans': 'academic',
  'lessons': 'academic',
  'curriculum': 'academic',
  'academic_meetings': 'academic',
  'at_risk': 'attendance',
  'attendance_insights': 'attendance',
  'health': 'student_affairs',
  'counseling': 'student_affairs',
  'iep': 'student_affairs',
  'special_needs': 'student_affairs',
  'college_guidance': 'student_affairs',
  'student_support': 'student_affairs',
  'clubs': 'student_affairs',
  'gojo': 'student_affairs',
  'scholarships': 'student_affairs',
  'grievances': 'student_affairs',
  'internships': 'student_affairs',
  'leadership_meetings': 'student_affairs',
  'leadership_tasks': 'student_affairs',
  'student_programs': 'student_affairs',
  'dosa': 'student_affairs',
  'analytics': 'attendance',
  'academic_analytics': 'attendance',
  'surveys': 'quality_assurance',
  'qa_surveys': 'quality_assurance',
  'observations': 'quality_assurance',
  'academic_audits': 'quality_assurance',
  'action_research': 'quality_assurance',
  'academic_monitoring': 'quality_assurance',
  'go_live': 'go_live',
  'golive': 'go_live',
  'compliance': 'go_live',
  'privacy': 'go_live',
  'privacy_rights': 'go_live',
  'data_rights': 'go_live',
  'backups': 'go_live',
  'training_manuals': 'go_live',
  'mfa': 'go_live',
  'ict': 'digital_ops',
  'devices': 'digital_ops',
  'gallery': 'events',
};

String normalizeModuleId(String moduleId) =>
    kModuleIdAliases[moduleId] ?? moduleId;
